services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress_app
    ports:
      - "8083:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: wpdatabase
    volumes:
      - wordpress_data:/var/www/html
    restart: always

volumes:
  wordpress_data: